//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormationWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscription
    {
        public int numAgent { get; set; }
        public int numFormation { get; set; }
        public int presence { get; set; }
        public int nbKm { get; set; }
    
        public virtual agent agent { get; set; }
        public virtual formation formation { get; set; }
    }
}
